# Site settings
title: Colm Howard-Lloyd
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Colm Howard-Lloyd
user_description: Description
# user_title: Software Engineer
email: colm@truthmonkey.org
twitter_username: colmhowardlloyd
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
